Controllers/EmployeeManagementController.cs
using Lab02.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab02.Controllers
{
    public class EmployeeManagementController : Controller
    {
        // GET: EmployeeManagement
        /// <summary>
        /// phương thức này có view là form để hiển thị dữ liệu
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Input()
        {
            return View();
        }

        [HttpPost]   // giao thức http POST, dùng để đưa dữ liệu từ phía client -> server
        // phương thức này nhận dữ liệu từ form phía client và xử lý
        public ActionResult CalSalaryV1()
        {
            string id = Request["id"];
            string name = Request["name"];
            int amount = int.Parse(Request["amount"]);
            double salary = double.Parse(Request["salary"]);
            Employee e = new Employee(id, name, amount, salary);
            return View(e);
        }


        [HttpPost]
        public ActionResult CalSalaryV2(string id, string name, int amount, double salary)
        {
            Employee e = new Employee(id, name, amount, salary);

            return View("CalSalaryV1", e); // dùng chung 1 view là CalSalaryV1, trả về 1 đối tượng Employee - Model
        }
        [HttpPost]
        public ActionResult CalSalaryV3(Employee emp)
        {
            ViewData["test"] = "test";
            return View("CalSalaryV1",emp);
        }

        [HttpPost]
        public ActionResult CalSalaryV4(Employee emp, FormCollection form)
        {
            emp.id = form["id"];
            emp.name = form["name"];
            emp.amount = int.Parse(form["amount"]);
            emp.salary = double.Parse(form["salary"]);


            return View("CalSalaryV1", emp);
        }
    }
}

Views/EmployeeManagement/CalSalaryV1.cshtml
@{
    ViewBag.Title = "CalSalaryV1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    ul > li {
        list-style: none;
    }
</style>

<div>
    <h2>Calculate Salary V1</h2>
    <ul>
        <li>Id: @Model.id</li>
        <li>Name: @Model.name</li>
        <li>Amount: @Model.amount</li>
        <li>Salary: @Model.salary</li>
        <li>Bonus: @Model.bonus</li>
        <li>Total: @Model.total</li>
    </ul>
</div>

Views/EmployeeManagement/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    label {
        width: 120px;
        float: left;
    }
</style>
<h2>Input Employee Information</h2>

<form action="CalSalaryV4" method="post">
    <p>
        <label>id</label>
        <input type="text" name="id" />
    </p>
    <p>
        <label>name</label>
        <input type="text" name="name" />
    </p>
    <p>
        <label>amount</label>
        <input type="text" name="amount" />
    </p>
    <p>
        <label>salary</label>
        <input type="text" name="salary" />
    </p>
    <p>
        <input type="submit" name="sb" class="bg-primary" value="Send to server!" />
    </p>
</form>

Views/EmployeeManagement/Input.cshtml
@model Lab02.Models.Employee

@{
    ViewBag.Title = "Input";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Input</h2>

@using (Html.BeginForm("CalSalaryV4", "EmployeeManagement"))
{
    <table>
        <tr>
            <td>Id</td>
            <td>@Html.TextBoxFor(model => model.id)</td>
        </tr>
        <tr>
            <td>Name</td>
            <td>@Html.TextBoxFor(model => model.name)</td>
        </tr>
        <tr>
            <td>Amount</td>
            <td>@Html.TextBoxFor(model => model.amount)</td>
        </tr>
        <tr>
            <td>Salary</td>
            <td>@Html.TextBoxFor(model => model.salary)</td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" name="sb" value="Send to server" />
            </td>
        </tr>
    </table>
}